services:
  backend:
    build:
      context: ./backend
    depends_on:
      - database
      - translator
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}"
      FRONTEND_URL: ${FRONTEND_URL}
      TRANSLATOR_URL: ${TRANSLATOR_URL}
      ENVIRONMENT: ${ENVIRONMENT}


  database:
    build:
      context: ./database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  frontend:
    build:
      context: ./frontend
    environment:
      BACKEND_URL: ${BACKEND_URL}
      ENVIRONMENT: ${ENVIRONMENT}
    ports:
      - "3001:3001"
    depends_on:
      - backend

  translator:
    build:
      context: ./translator
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
