"""Changed tables for saving word translations

Revision ID: 083cf1a21542
Revises: 681e988de1f7
Create Date: 2025-03-14 19:02:34.684264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083cf1a21542'
down_revision: Union[str, None] = '681e988de1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_en',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('word_ua',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('word_translation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word_ua_id', sa.Integer(), nullable=False),
    sa.Column('word_en_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_en_id'], ['word_en.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_ua_id'], ['word_ua.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_translation')
    op.drop_table('word_ua')
    op.drop_table('word_en')
    # ### end Alembic commands ###
