"""Added sentences translation knowledge

Revision ID: 245b7f917f13
Revises: 5ea8bbc56486
Create Date: 2025-04-10 16:53:25.705454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245b7f917f13'
down_revision: Union[str, None] = '5ea8bbc56486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_translation_knowledge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sentence_translation_id', sa.Integer(), nullable=False),
    sa.Column('knowledge', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['sentence_translation_id'], ['sentence_translation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['my_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_translation_knowledge')
    # ### end Alembic commands ###
