"""Added word translation knowledge table

Revision ID: 2c394ea3597a
Revises: 4581e156b232
Create Date: 2025-03-28 21:42:08.628393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c394ea3597a'
down_revision: Union[str, None] = '4581e156b232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_translation_knowledge',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_translation_id', sa.Integer(), nullable=False),
    sa.Column('knowledge', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['my_user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_translation_id'], ['word_translation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_translation_knowledge')
    # ### end Alembic commands ###
