"""Added sentences and their translations

Revision ID: 5ea8bbc56486
Revises: 2c394ea3597a
Create Date: 2025-04-07 16:09:11.705266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea8bbc56486'
down_revision: Union[str, None] = '2c394ea3597a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
    sa.Column('sentence', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sentence')
    )
    op.create_table('sentence_translation',
    sa.Column('sentence_original_id', sa.Integer(), nullable=False),
    sa.Column('sentence_translated_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['sentence_original_id'], ['sentence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_translated_id'], ['sentence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence_translation')
    op.drop_table('sentence')
    # ### end Alembic commands ###
