"""Added table with words translations to ua

Revision ID: e19c2918f07d
Revises: 681e988de1f7
Create Date: 2025-03-13 14:16:24.547687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19c2918f07d'
down_revision: Union[str, None] = '681e988de1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words_to_ua',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_word', sa.String(), nullable=False),
    sa.Column('translated_word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words_to_ua')
    # ### end Alembic commands ###
